keycfg = {
    'p1_up':    'up',
    'p1_down':  'down',
    'p1_left':  'left',
    'p1_right': 'right',
    'p1_1':     'leftcontrol',
    'p1_2':     'leftalt',
    'p1_3':     'space',
    'p1_4':     'leftshift',
    'p1_5':     'z',
    'p1_6':     'x',
    'p1_7':     'c',
    'p1_8':     'v',
    'p1_a':     'p',
    'p1_b':     'enter',
    'p1_coin':  '5',
    'p1_start': '1',

    'p2_up':    'r',
    'p2_down':  'f',
    'p2_left':  'd',
    'p2_right': 'g',
    'p2_1':     'a',
    'p2_2':     's',
    'p2_3':     'q',
    'p2_4':     'w',
    'p2_5':     'i',
    'p2_6':     'k',
    'p2_7':     'j',
    'p2_8':     'l',
    'p2_a':     'tab',
    'p2_b':     'esc',
    'p2_coin':  '6',
    'p2_start': '2',
}


emulationstation_mapping = {
    'up':            'p1_up',
    'down':          'p1_down',
    'left':          'p1_left',
    'right':         'p1_right',
    'b':             'p1_1',
    'a':             'p1_2',
    'rightshoulder': 'p1_3',
    'y':             'p1_4',
    'x':             'p1_5',
    'leftshoulder':  'p1_6',
    'righttrigger':  'p1_7',
    'lefttrigger':   'p1_8',
    'hotkeyenable':  'p1_a',
    'select':        'p1_coin',
    'start':         'p1_start',
}
